function [ tdc ] = TotalDiscountedCost( c,a,cDiscount,pdf )
tdc = @(limit) (integral(pdf, limit, Inf(1)).*exp(-cDiscount.*limit)...
        +integral(@(t) pdf(t).*exp(-cDiscount.*t),0,limit).*(c+a))...
    /(1-integral(pdf, limit, Inf(1)).*exp(-cDiscount.*limit)...
        -integral(@(t) pdf(t).*exp(-cDiscount.*t),0,limit));
end
