function [ tdc ] = TotalDiscountedCost( c,a,cDiscount,pdf )
%TOTALDISCOUNTEDCOST Returns a function handle that takes a control limit 
%as input an gives the expected total discounted cost corresponding to the 
%age-based problem with the given parameters.
tdc = @(limit) (integral(pdf, limit, Inf(1)).*exp(-cDiscount.*limit)...
        +integral(@(t) pdf(t).*exp(-cDiscount.*t),0,limit).*(c+a))...
    /(1-integral(pdf, limit, Inf(1)).*exp(-cDiscount.*limit)...
        -integral(@(t) pdf(t).*exp(-cDiscount.*t),0,limit));
end
